#!/bin/bash
# fvwm-menu-clipboard
# by greatant
# https://github.com/greatant/fvwm-pipemenus/
#
# Requires: clipbored, xsel
#====================================================

IFS=$'\n'

echo "DestroyMenu recreate FvwmMenuClip"
echo "AddToMenu FvwmMenuClip"

for i in $(cat $XDG_DATA_HOME/clipbored/clips | tail -n $1); do
	echo "+ \"${i:0:50}\" Exec 'echo \"${i}\" | xclip -i -selection secondary'"; done

echo "+ \"\" Nop"
echo "+ \"Clear\" Exec exec clipbored --clear"
 
unset IFS
