#!/bin/bash
# fvwm-menu-netcfg
# by greatant v1

dif(){
  awk 'BEGIN{RS=ORS=" "}
       {NR==FNR?a[$0]++:a[$0]--}
       END{for(k in a)if(a[k])print k}' <(echo -n "${!1}") <(echo -n "${!2}")
}

PROFILEDIR="/etc/network.d/"
ACTIVEPROFILE=( $(netcfg current) )
ALLPROFILE=( $(netcfg list) )
INACTIVEPROFILE=( $(dif ALLPROFILE[@] ACTIVEPROFILE[@]) )


echo "DestroyMenu recreate FvwmMenuNetcfg"
echo "AddToMenu FvwmMenuNetcfg \"Scan\" Popup FvwmMenuNetcfgScan"

if [ ${#ACTIVEPROFILE[@]} -gt 0 ]; then
	echo "AddToMenu FvwmMenuNetcfg \"Active profiles\" Title"
	for i in ${ACTIVEPROFILE[@]}; do . "$PROFILEDIR$i"
		echo "AddToMenu FvwmMenuNetcfg \"$i ($INTERFACE)%$CONNECTION.png%\" Exec sudo netcfg down $i"; done
fi

echo "AddToMenu FvwmMenuNetcfg \"Inactive profiles\" Title"

for i in ${INACTIVEPROFILE[@]}; do
	. "$PROFILEDIR$i"
	echo "AddToMenu FvwmMenuNetcfg \"$i%$CONNECTION.png%\" Exec sudo netcfg $i"; done
